name: Main push SAST

on:
  pull_request:
    branches:
      - main
    paths:
      - ".github/actions/**"
      - ".github/workflows/**"
      - "**/*.cjs"
      - "**/*.cts"
      - "**/*.js"
      - "**/*.jsx"
      - "**/*.mjs"
      - "**/*.mts"
      - "**/*.py"
      - "**/*.ts"
      - "**/*.tsx"
  push:
    branches:
      - main
    paths:
      - ".github/actions/**"
      - ".github/workflows/**"
      - "**/*.cjs"
      - "**/*.cts"
      - "**/*.js"
      - "**/*.jsx"
      - "**/*.mjs"
      - "**/*.mts"
      - "**/*.py"
      - "**/*.ts"
      - "**/*.tsx"
  merge_group:
    types:
      - checks_requested
  workflow_dispatch:

permissions:
  contents: read

concurrency:
  group: security-${{ github.workflow }}-${{ github.event.pull_request.number || github.event.merge_group.head_ref || github.ref }}
  cancel-in-progress: true

jobs:
  sast:
    name: SAST
    uses: ./.github/workflows/security-sast.yml
    permissions:
      contents: read
      security-events: write
